#!/usr/bin/env python3
"""Regenerate docs/progress.md from the stored baselines.

Generated, never hand-edited. A coverage table maintained by hand drifts from
the measurements the moment anyone forgets to update it, and a stale number
here is worse than none -- the whole point is to run something, re-measure, and
see whether the count moved.

    scripts/score-juliet.py third_party/juliet/C --limit 40 \
        --json-out data/juliet-baseline.json
    scripts/progress.py
"""

import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Tier from docs/cwe-difficulty.md, which explains what each one means. Kept
# here as a plain letter so the table can be sorted by cost-to-close.
TIER = {
    483: "A", 563: "A", 562: "A",
    415: "B", 762: "B", 476: "B", 401: "B",
    252: "C", 369: "C", 124: "C", 121: "C", 127: "C",
    126: "D", 122: "D", 680: "D", 190: "D",
    416: "E", 590: "E", 665: "E", 690: "E", 775: "E",
    191: "F", 197: "F",
    843: "G", 672: "G",
    457: "B",
}

# What would move the number, per CWE. Empty means "working, revisit last".
NEXT = {
    121: "the `_large_` family assigns a constant out of range -- no call involved, so the index checks skip it",
    122: "value-range; try `--ikos` and measure",
    126: "`--ikos` takes this to 86%; decide whether it becomes default or the report says what it is worth",
    127: "`memcpy` source overruns with a runtime length",
    190: "IKOS proves the constant cases; ~71% need a bound on external input and are unprovable",
    191: "defined behaviour -- move to Advice rather than chasing recall",
    197: "defined behaviour -- same",
    252: "widen CHECKED_FUNCTIONS only where ignoring the result uses an uncomputed value",
    369: "the remaining misses are socket and fscanf sources",
    416: "`--ctu` takes the split cases 0% -> 30%",
    457: "",
    476: "",
    483: "",
    562: "half the flawed functions are wrappers calling the helper; 50% is the ceiling",
    563: "",
    590: "triage the shapes -- never done",
    665: "the fallible-constructor class; `--ctu` is the lever",
    672: "needs a per-resource lifetime model; leave until the ownership pass exists",
    680: "18.3% FP is the widest accept set here -- check it before trusting the recall",
    690: "a chain: 252 and 476 are 70% and 84% separately. Join them rather than detect anything new",
    775: "static is 16%; the dynamic layer gets 100% with valgrind --track-fds",
    843: "needs to know which union member is live -- application knowledge, not analysis",
    401: "",
    415: "",
    762: "",
    124: "",
}


def main():
    base = json.load(open(os.path.join(HERE, "data/juliet-baseline.json")))
    dyn = json.load(open(os.path.join(HERE, "data/juliet-dynamic-baseline.json")))
    names = {}
    import re
    for m in re.finditer(r'\[\[cwe\]\]\nid = (\d+)\nname = "([^"]+)"',
                         open(os.path.join(HERE, "data/cwe_map.toml")).read()):
        names[int(m.group(1))] = m.group(2)

    rows = []
    for k, v in base.items():
        cwe = int(k)
        d = dyn.get(k)
        rows.append({
            "cwe": cwe,
            "tier": TIER.get(cwe, "?"),
            "name": names.get(cwe, "?"),
            "found": v["bad_found"], "total": v["bad_total"],
            "surfaced": v["bad_found_surfaced"],
            "fp": v["good_flagged"], "good": v["good_total"],
            "dyn": f'{d["caught"]}/{d["runnable"]}' if d and d["runnable"] else "—",
            "next": NEXT.get(cwe, ""),
        })
    rows.sort(key=lambda r: (r["tier"], -r["found"] / r["total"] if r["total"] else 0))

    tf = sum(r["found"] for r in rows)
    tt = sum(r["total"] for r in rows)
    ts = sum(r["surfaced"] for r in rows)
    tfp = sum(r["fp"] for r in rows)
    tg = sum(r["good"] for r in rows)

    L = []
    L.append("# Coverage progress\n")
    L.append("**Generated by `scripts/progress.py`. Do not hand-edit** — a coverage table")
    L.append("maintained by hand drifts from the measurements, and a stale number here is")
    L.append("worse than none.\n")
    L.append(f"## {tf}/{tt} flawed functions found ({100*tf/tt:.1f}%)\n")
    L.append(f"- **{ts}/{tt} ({100*ts/tt:.1f}%) surfaced** — high and medium confidence, what the")
    L.append("  report shows without `--all`. This is the number a user actually sees.")
    L.append(f"- **{tfp}/{tg} ({100*tfp/tg:.1f}%) correct functions flagged.**")
    L.append("- Static layer, default flags. `--ikos` and `--ctu` add more; the dynamic")
    L.append("  column is a separate run and **must not be added to the static one**.\n")
    L.append("### What 'total' means here\n")
    L.append("The denominator is the **40-file sample per CWE**, not the whole suite —")
    L.append("Juliet has 101,231 files and CWE-121 alone has 7,889. Raising `--limit`")
    L.append("changes both numbers, so only compare runs at the same limit. 100% of the")
    L.append("sample is not 100% of Juliet, and neither is the goal on its own: the")
    L.append("suite is synthetic, and `docs/juliet-inventory.md` says why its scores do")
    L.append("not transfer to real code.\n")
    L.append("| tier | CWE | name | found/total | surfaced | FP | dynamic | what would move it |")
    L.append("|---|---|---|---|---|---|---|---|")
    for r in rows:
        L.append(f"| {r['tier']} | {r['cwe']} | {r['name'][:34]} | "
                 f"**{r['found']}/{r['total']}** | {r['surfaced']} | {r['fp']}/{r['good']} | "
                 f"{r['dyn']} | {r['next']} |")
    L.append("\nTiers are from `docs/cwe-difficulty.md`: **A** the compiler already knows,")
    L.append("**B** a default checker does it, **C** a shape rule Kordon writes, **D** needs")
    L.append("a value bound, **E** cross-TU or ownership, **F** defined behaviour that no")
    L.append("tool can decide, **G** needs semantics no analyzer has.\n")
    open(os.path.join(HERE, "docs/progress.md"), "w").write("\n".join(L) + "\n")
    print(f"docs/progress.md: {tf}/{tt} found, {ts} surfaced, {tfp}/{tg} FP")


if __name__ == "__main__":
    main()
